// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostHelloOKCode is the HTTP code returned for type PostHelloOK
const PostHelloOKCode int = 200

/*PostHelloOK OK

swagger:response postHelloOK
*/
type PostHelloOK struct {

	/*
	  In: Body
	*/
	Payload *PostHelloOKBody `json:"body,omitempty"`
}

// NewPostHelloOK creates PostHelloOK with default headers values
func NewPostHelloOK() *PostHelloOK {

	return &PostHelloOK{}
}

// WithPayload adds the payload to the post hello o k response
func (o *PostHelloOK) WithPayload(payload *PostHelloOKBody) *PostHelloOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post hello o k response
func (o *PostHelloOK) SetPayload(payload *PostHelloOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostHelloOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
